/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by routing generator. DO NOT EDIT.

package coze

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	coze "github.com/coze-dev/coze-studio/backend/api/handler/coze/routing"
)

// RegisterRoutingRoutes 注册智能路由相关的所有路由
func RegisterRoutingRoutes(r *server.Hertz, handlers *coze.RoutingHandlers) {
	root := r.Group("/")
	{
		_api := root.Group("/api")
		{
			_routing := _api.Group("/routing")
			{
				// ==================== 意图识别路由 ====================
				_intents := _routing.Group("/intents")
				_intents.POST("/recognize", handlers.IntentRecognition.RecognizeIntent)
				_intents.POST("/batch", handlers.IntentRecognition.BatchRecognize)
				_intents.GET("", handlers.IntentRecognition.GetIntents)
				_intents.POST("", handlers.IntentRecognition.UpdateIntent) // 创建也用POST
				_intents.PUT("/:id", handlers.IntentRecognition.UpdateIntent)
				_intents.DELETE("/:id", handlers.IntentRecognition.DeleteIntent)
				_intents.POST("/:id/train", handlers.IntentRecognition.TrainIntentModel)

				// ==================== 路由优化路由 ====================
				_optimizer := _routing.Group("/optimizer")
				_optimizer.POST("/optimize", handlers.RoutingOptimizer.OptimizeRouting)
				_optimizer.POST("/optimal-agent", handlers.RoutingOptimizer.GetOptimalAgent)
				_optimizer.POST("/predict-load", handlers.RoutingOptimizer.PredictAgentLoad)
				_optimizer.POST("/config", handlers.RoutingOptimizer.SetOptimizerConfig)
				_optimizer.GET("/config", handlers.RoutingOptimizer.GetOptimizerConfig)

				// ==================== 路由规则配置路由 ====================
				_rules := _routing.Group("/rules")
				_rules.POST("", handlers.RoutingRuleConfig.CreateRule)
				_rules.PUT("/:id", handlers.RoutingRuleConfig.UpdateRule)
				_rules.GET("/:id", handlers.RoutingRuleConfig.GetRule)
				_rules.DELETE("/:id", handlers.RoutingRuleConfig.DeleteRule)
				_rules.GET("", handlers.RoutingRuleConfig.ListRules)
				_rules.POST("/:id/enable", handlers.RoutingRuleConfig.EnableRule)
				_rules.POST("/:id/disable", handlers.RoutingRuleConfig.DisableRule)
				_rules.POST("/validate", handlers.RoutingRuleConfig.ValidateRule)
				_rules.POST("/:id/test", handlers.RoutingRuleConfig.TestRule)

				// ==================== A/B测试路由 ====================
				_abtests := _routing.Group("/abtests")
				_abtests.POST("", handlers.ABTest.CreateABTest)
				_abtests.GET("", handlers.ABTest.ListABTests)
				_abtests.POST("/:id/execute", handlers.ABTest.ExecuteABTest)
				_abtests.GET("/:id/results", handlers.ABTest.GetABTestResults)
				_abtests.POST("/:id/conclude", handlers.ABTest.ConcludeABTest)

				// ==================== 路由学习路由 ====================
				_learning := _routing.Group("/learning")
				_learning.POST("/analyze", handlers.RoutingLearning.LearnFromLogs)
				_learning.POST("/suggest-rules", handlers.RoutingLearning.SuggestRules)
				_learning.POST("/optimize-strategy", handlers.RoutingLearning.OptimizeStrategy)
				_learning.GET("/progress", handlers.RoutingLearning.GetLearningProgress)
				_learning.POST("/export-report", handlers.RoutingLearning.ExportLearningReport)
			}
		}
	}
}
