// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSession = "session"

// Session Session Table
// 会话表，用于存储用户会话信息
type Session struct {
	UserID    int64     `gorm:"column:user_id;not null;comment:User ID" json:"user_id"`                               // User ID
	TenantID  string    `gorm:"column:tenant_id;type:varchar(64);comment:租户ID（多租户隔离）" json:"tenant_id"`         // 租户ID（多租户隔离）
	Locale    string    `gorm:"column:locale;not null;comment:Locale" json:"locale"`                                  // Locale
	UserEmail string    `gorm:"column:user_email;not null;comment:User Email" json:"user_email"`                      // User Email
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:Creation Time" json:"created_at"` // Creation Time
	ExpiresAt time.Time `gorm:"column:expires_at;not null;comment:Expiration Time" json:"expires_at"`                  // Expiration Time
}

// TableName Session's table name
func (*Session) TableName() string {
	return TableNameSession
}
