// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
	"gorm.io/gorm"
)

const TableNameUserTenant = "user_tenant"

// UserTenant User-Tenant Relation Table
// 用户-租户关联表，支持用户多租户场景
type UserTenant struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                       // 主键ID
	UserID    int64          `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                 // 用户ID
	TenantID  string         `gorm:"column:tenant_id;type:varchar(64);not null;comment:租户ID" json:"tenant_id"`            // 租户ID
	Role      string         `gorm:"column:role;type:varchar(64);not null;default:'member';comment:角色" json:"role"`       // 角色: owner, admin, member
	IsDefault bool           `gorm:"column:is_default;not null;default:0;comment:是否为默认租户" json:"is_default"`            // 是否为默认租户
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间（软删除）" json:"deleted_at"`                           // 删除时间（软删除）
}

// TableName UserTenant's table name
func (*UserTenant) TableName() string {
	return TableNameUserTenant
}
