/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator.

package coze

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	"github.com/coze-dev/coze-studio/backend/api/model/data/variable/kvmemory"
	"github.com/coze-dev/coze-studio/backend/api/internal/httputil"
	"github.com/coze-dev/coze-studio/backend/api/model/data/variable/project_memory"
	appApplication "github.com/coze-dev/coze-studio/backend/application/app"
	"github.com/coze-dev/coze-studio/backend/application/memory"
	"github.com/coze-dev/coze-studio/backend/pkg/lang/conv"
)

// GetSysVariableConf .
// @router /api/memory/sys_variable_conf [GET]
func GetSysVariableConf(ctx context.Context, c *app.RequestContext) {
	var err error
	var req kvmemory.GetSysVariableConfRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := memory.VariableApplicationSVC.GetSysVariableConf(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// GetProjectVariableList .
// @router /api/memory/project/variable/meta_list [GET]
func GetProjectVariableList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req project_memory.GetProjectVariableListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if req.ProjectID == "" {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "project_id is empty", "参数验证失败", nil)
		return
	}

	pID, err := conv.StrToInt64(req.ProjectID)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "project_id is not int", "参数验证失败", nil)
		return
	}

	pInfo, err := appApplication.APPApplicationSVC.DomainSVC.GetDraftAPP(ctx, pID)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	resp, err := memory.VariableApplicationSVC.GetProjectVariablesMeta(ctx, pInfo.OwnerID, &req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// UpdateProjectVariable .
// @router /api/memory/project/variable/meta_update [POST]
func UpdateProjectVariable(ctx context.Context, c *app.RequestContext) {
	var err error
	var req project_memory.UpdateProjectVariableReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if req.ProjectID == "" {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "project_id is empty", "参数验证失败", nil)
		return
	}

	key2Var := make(map[string]*project_memory.Variable)
	for _, v := range req.VariableList {
		if v.Keyword == "" {
			httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "variable name is empty", "参数验证失败", nil)
			return
		}

		if key2Var[v.Keyword] != nil {
			httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "variable keyword is duplicate", "参数验证失败", nil)
			return
		}

		key2Var[v.Keyword] = v
	}

	resp, err := memory.VariableApplicationSVC.UpdateProjectVariable(ctx, req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// SetKvMemory .
// @router /api/memory/variable/upsert [POST]
func SetKvMemory(ctx context.Context, c *app.RequestContext) {
	var err error
	var req kvmemory.SetKvMemoryReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if req.BotID == 0 && req.GetProjectID() == "" {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "bot_id and project_id are both empty", "参数验证失败", nil)
		return
	}

	if len(req.Data) == 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "data is empty", "参数验证失败", nil)
		return
	}

	resp, err := memory.VariableApplicationSVC.SetVariableInstance(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// GetMemoryVariableMeta .
// @router /api/memory/variable/get_meta [POST]
func GetMemoryVariableMeta(ctx context.Context, c *app.RequestContext) {
	var err error
	var req project_memory.GetMemoryVariableMetaReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := memory.VariableApplicationSVC.GetVariableMeta(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// DelProfileMemory .
// @router /api/memory/variable/delete [POST]
func DelProfileMemory(ctx context.Context, c *app.RequestContext) {
	var err error
	var req kvmemory.DelProfileMemoryRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if req.BotID == 0 && req.GetProjectID() == "" {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "bot_id and project_id are both empty", "参数验证失败", nil)
		return
	}

	resp, err := memory.VariableApplicationSVC.DeleteVariableInstance(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// GetPlayGroundMemory .
// @router /api/memory/variable/get [POST]
func GetPlayGroundMemory(ctx context.Context, c *app.RequestContext) {
	var err error
	var req kvmemory.GetProfileMemoryRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if req.BotID == 0 && req.GetProjectID() == "" {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "bot_id and project_id are both empty", "参数验证失败", nil)
		return
	}

	resp, err := memory.VariableApplicationSVC.GetPlayGroundMemory(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}
