/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator.

package coze

import (
	"context"
	"regexp"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	"github.com/coze-dev/coze-studio/backend/api/model/plugin_develop"
	"github.com/coze-dev/coze-studio/backend/api/internal/httputil"
	common "github.com/coze-dev/coze-studio/backend/api/model/plugin_develop/common"
	"github.com/coze-dev/coze-studio/backend/application/plugin"
	appworkflow "github.com/coze-dev/coze-studio/backend/application/workflow"
)

// GetPlaygroundPluginList .
// @router /api/plugin_api/get_playground_plugin_list [POST]
func GetPlaygroundPluginList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.GetPlaygroundPluginListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.GetSpaceID() <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "spaceID is invalid", "参数验证失败", nil)
		return
	}
	if req.GetPage() <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "page is invalid", "参数验证失败", nil)
		return
	}
	if req.GetSize() >= 30 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "size is invalid", "参数验证失败", nil)
		return
	}

	// when there is only one element in the types list, and the element type is workflow, use workflow service
	// TODO Figure out when there are multiple values for types
	if len(req.GetPluginTypes()) == 1 && req.GetPluginTypes()[0] == int32(common.PluginType_WORKFLOW) {
		resp, err := appworkflow.SVC.GetPlaygroundPluginList(ctx, &req)
		if err != nil {
			httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
			return
		}
		httputil.BuildSuccessResp(c, resp)
		return
	}

	resp, err := plugin.PluginApplicationSVC.GetPlaygroundPluginList(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// RegisterPluginMeta .
// @router /api/plugin_api/register_plugin_meta [POST]
func RegisterPluginMeta(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.RegisterPluginMetaRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.GetName() == "" {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "plugin name is invalid", "参数验证失败", nil)
		return
	}
	if req.GetDesc() == "" {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "plugin desc is invalid", "参数验证失败", nil)
		return
	}
	if req.URL != nil && (*req.URL == "" || len(*req.URL) > 512) {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "plugin url is invalid", "参数验证失败", nil)
		return
	}
	if req.Icon == nil || req.Icon.URI == "" || len(req.Icon.URI) > 512 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "plugin icon is invalid", "参数验证失败", nil)
		return
	}
	if req.AuthType == nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "plugin auth type is invalid", "参数验证失败", nil)
		return
	}
	if req.SpaceID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "spaceID is invalid", "参数验证失败", nil)
		return
	}
	if req.ProjectID != nil {
		if *req.ProjectID <= 0 {
			httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "projectID is invalid", "参数验证失败", nil)
			return
		}
	}
	if req.GetPluginType() != common.PluginType_PLUGIN {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "plugin type is invalid", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.RegisterPluginMeta(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// GetPluginAPIs .
// @router /api/plugin_api/get_plugin_apis [POST]
func GetPluginAPIs(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.GetPluginAPIsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.PluginID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "pluginID is invalid", "参数验证失败", nil)
		return
	}
	if len(req.APIIds) == 0 {
		if req.Page <= 0 {
			httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "page is invalid", "参数验证失败", nil)
			return
		}
		if req.Size >= 30 {
			httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "size is invalid", "参数验证失败", nil)
			return
		}
	}

	resp, err := plugin.PluginApplicationSVC.GetPluginAPIs(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// GetPluginInfo .
// @router /api/plugin_api/get_plugin_info [POST]
func GetPluginInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.GetPluginInfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.PluginID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "pluginID is invalid", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.GetPluginInfo(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// GetUpdatedAPIs .
// @router /api/plugin_api/get_updated_apis [POST]
func GetUpdatedAPIs(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.GetUpdatedAPIsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.PluginID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "pluginID is invalid", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.GetUpdatedAPIs(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// GetOAuthStatus .
// @router /api/plugin_api/get_oauth_status [POST]
func GetOAuthStatus(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.GetOAuthStatusRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.PluginID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "pluginID is invalid", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.GetOAuthStatus(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// CheckAndLockPluginEdit .
// @router /api/plugin_api/check_and_lock_plugin_edit [POST]
func CheckAndLockPluginEdit(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.CheckAndLockPluginEditRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.PluginID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "pluginID is invalid", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.CheckAndLockPluginEdit(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// UpdatePlugin .
// @router /api/plugin_api/update [POST]
func UpdatePlugin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.UpdatePluginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.PluginID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "pluginID is invalid", "参数验证失败", nil)
		return
	}
	if req.AiPlugin == "" {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "plugin manifest is invalid", "参数验证失败", nil)
		return
	}
	if req.Openapi == "" {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "plugin openapi doc is invalid", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.UpdatePlugin(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// DeleteAPI .
// @router /api/plugin_api/delete_api [POST]
func DeleteAPI(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.DeleteAPIRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.PluginID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "pluginID is invalid", "参数验证失败", nil)
		return
	}
	if req.APIID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "apiID is invalid", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.DeleteAPI(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// DelPlugin .
// @router /api/plugin_api/del_plugin [POST]
func DelPlugin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.DelPluginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.PluginID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "pluginID is invalid", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.DelPlugin(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// PublishPlugin .
// @router /api/plugin_api/publish_plugin [POST]
func PublishPlugin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.PublishPluginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.PluginID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "pluginID is invalid", "参数验证失败", nil)
		return
	}
	if req.VersionName == "" || len(req.VersionName) > 255 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "version name is invalid", "参数验证失败", nil)
		return
	}

	match, _ := regexp.MatchString(`^v\d+\.\d+\.\d+$`, req.VersionName)
	if !match {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "version name is invalid", "参数验证失败", nil)
		return
	}

	if req.VersionDesc == "" {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "version desc is invalid", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.PublishPlugin(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// UpdatePluginMeta .
// @router /api/plugin_api/update_plugin_meta [POST]
func UpdatePluginMeta(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.UpdatePluginMetaRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.PluginID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "pluginID is invalid", "参数验证失败", nil)
		return
	}
	if req.Name != nil && *req.Name == "" {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "plugin name is invalid", "参数验证失败", nil)
		return
	}
	if req.Desc != nil && *req.Desc == "" {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "plugin desc is invalid", "参数验证失败", nil)
		return
	}
	if req.URL != nil && (*req.URL == "" || len(*req.URL) > 512) {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "plugin server url is invalid", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.UpdatePluginMeta(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// GetBotDefaultParams .
// @router /api/plugin_api/get_bot_default_params [POST]
func GetBotDefaultParams(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.GetBotDefaultParamsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.SpaceID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "spaceID is invalid", "参数验证失败", nil)
		return
	}
	if req.BotID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "botID is invalid", "参数验证失败", nil)
		return
	}
	if req.PluginID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "pluginID is invalid", "参数验证失败", nil)
		return
	}
	if req.APIName == "" {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "apiName is invalid", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.GetBotDefaultParams(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// UpdateBotDefaultParams .
// @router /api/plugin_api/update_bot_default_params [POST]
func UpdateBotDefaultParams(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.UpdateBotDefaultParamsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.SpaceID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "spaceID is invalid", "参数验证失败", nil)
		return
	}
	if req.BotID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "botID is invalid", "参数验证失败", nil)
		return
	}
	if req.PluginID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "pluginID is invalid", "参数验证失败", nil)
		return
	}
	if req.APIName == "" {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "apiName is invalid", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.UpdateBotDefaultParams(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// CreateAPI .
// @router /api/plugin_api/create_api [POST]
func CreateAPI(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.CreateAPIRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.PluginID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "pluginID is invalid", "参数验证失败", nil)
		return
	}
	if req.Name == "" || len(req.Name) > 255 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "api name is invalid", "参数验证失败", nil)
		return
	}
	if req.Desc == "" {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "api desc is invalid", "参数验证失败", nil)
		return
	}
	if req.Path != nil && (*req.Path == "" || len(*req.Path) > 512) {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "api path is invalid", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.CreateAPI(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// UpdateAPI .
// @router /api/plugin_api/update_api [POST]
func UpdateAPI(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.UpdateAPIRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.PluginID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "pluginID is invalid", "参数验证失败", nil)
		return
	}
	if req.APIID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "apiID is invalid", "参数验证失败", nil)
		return
	}
	if req.Name != nil && (*req.Name == "" || len(*req.Name) > 255) {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "api name is invalid", "参数验证失败", nil)
		return
	}
	if req.Desc != nil && (*req.Desc == "" || len(*req.Desc) > 255) {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "api desc is invalid", "参数验证失败", nil)
		return
	}
	if req.Path != nil && (*req.Path == "" || len(*req.Path) > 512) {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "api path is invalid", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.UpdateAPI(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// GetUserAuthority .
// @router /api/plugin_api/get_user_authority [POST]
func GetUserAuthority(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.GetUserAuthorityRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.PluginID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "pluginID is invalid", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.GetUserAuthority(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// DebugAPI .
// @router /api/plugin_api/debug_api [POST]
func DebugAPI(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.DebugAPIRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.PluginID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "pluginID is invalid", "参数验证失败", nil)
		return
	}
	if req.APIID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "apiID is invalid", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.DebugAPI(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// UnlockPluginEdit .
// @router /api/plugin_api/unlock_plugin_edit [POST]
func UnlockPluginEdit(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.UnlockPluginEditRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	resp, err := plugin.PluginApplicationSVC.UnlockPluginEdit(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// GetPluginNextVersion .
// @router /api/plugin_api/get_plugin_next_version [POST]
func GetPluginNextVersion(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.GetPluginNextVersionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	resp, err := plugin.PluginApplicationSVC.GetPluginNextVersion(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// RegisterPlugin .
// @router /api/developer/register [POST]
func RegisterPlugin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.RegisterPluginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.GetSpaceID() <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "spaceID is invalid", "参数验证失败", nil)
		return
	}
	if req.ProjectID != nil && *req.ProjectID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "projectID is invalid", "参数验证失败", nil)
		return
	}
	if req.AiPlugin == "" {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "plugin manifest is invalid", "参数验证失败", nil)
		return
	}
	if req.Openapi == "" {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "plugin openapi doc is invalid", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.RegisterPlugin(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// GetDevPluginList .
// @router /api/plugin_api/get_dev_plugin_list [POST]
func GetDevPluginList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.GetDevPluginListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.SpaceID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "spaceID is invalid", "参数验证失败", nil)
		return
	}
	if req.ProjectID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "projectID is invalid", "参数验证失败", nil)
		return
	}
	if req.GetPage() <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "page is invalid", "参数验证失败", nil)
		return
	}
	if req.GetSize() <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "size is invalid", "参数验证失败", nil)
		return
	}
	if req.GetSize() > 50 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "size is too large", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.GetDevPluginList(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// Convert2OpenAPI .
// @router /api/plugin_api/convert_to_openapi [POST]
func Convert2OpenAPI(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.Convert2OpenAPIRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.SpaceID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "spaceID is invalid", "参数验证失败", nil)
		return
	}
	if req.Data == "" {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "data is invalid", "参数验证失败", nil)
		return
	}
	if req.PluginURL != nil && *req.PluginURL == "" {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "pluginURL is invalid", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.Convert2OpenAPI(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// GetOAuthSchemaAPI .
// @router /api/plugin_api/get_oauth_schema [POST]
func GetOAuthSchemaAPI(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.GetOAuthSchemaRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	resp, err := plugin.PluginApplicationSVC.GetOAuthSchema(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// GetOAuthSchema .
// @router /api/plugin/get_oauth_schema [POST]
func GetOAuthSchema(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.GetOAuthSchemaRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	resp, err := plugin.PluginApplicationSVC.GetOAuthSchema(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// BatchCreateAPI .
// @router /api/plugin_api/batch_create_api [POST]
func BatchCreateAPI(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.BatchCreateAPIRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.SpaceID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "spaceID is invalid", "参数验证失败", nil)
		return
	}
	if req.PluginID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "pluginID is invalid", "参数验证失败", nil)
		return
	}
	if req.AiPlugin == "" {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "plugin manifest is invalid", "参数验证失败", nil)
		return
	}
	if req.Openapi == "" {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "plugin openapi doc is invalid", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.BatchCreateAPI(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// RevokeAuthToken .
// @router /api/plugin_api/revoke_auth_token [POST]
func RevokeAuthToken(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.RevokeAuthTokenRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.PluginID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "pluginID is invalid", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.RevokeAuthToken(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}

// GetQueriedOAuthPluginList .
// @router /api/plugin_api/get_queried_oauth_plugins [POST]
func GetQueriedOAuthPluginList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req plugin_develop.GetQueriedOAuthPluginListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, err.Error(, "参数验证失败", nil))
		return
	}

	if req.BotID <= 0 {
		httputil.BuildErrorResp(c, errno.ErrInvalidParamCode, "entityID is required", "参数验证失败", nil)
		return
	}

	resp, err := plugin.PluginApplicationSVC.GetQueriedOAuthPluginList(ctx, &req)
	if err != nil {
		httputil.BuildErrorRespFromEnhanced(c, errno.NewInternalError(ctx, err))
		return
	}

	httputil.BuildSuccessResp(c, resp)
}
